### ISSUE TITLE
Unhandled Error when loading try.mudblazor.com on Firefox

### ISSUE THREAD

**Issue by hburn7** [MudBlazor/TryMudBlazor#105]
When trying to load [try.mudblazor.com](https://try.mudblazor.com/) on Firefox, there is an unhandled error. No snippits can be loaded nor can the base site.

```
System.AggregateException: One or more errors occurred. (Could not resolve type with token 0100006c from typeref (expected class 'Try.UserComponents.__Main' in assembly 'Try.UserComponents, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'))
 ---> System.TypeLoadException: Could not resolve type with token 0100006c from typeref (expected class 'Try.UserComponents.__Main' in assembly 'Try.UserComponents, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null')
   at TryMudBlazor.Client.Program.Main(String[] args)
   --- End of inner exception stack trace --- blazor.webassembly.js:1:46102
    callEntryPoint https://try.mudblazor.com/_framework/blazor.webassembly.js:1
```

![firefox_WKZxCyO49O](https://user-images.githubusercontent.com/38370573/218268482-9608f2e7-0f9f-40d7-9d67-0702eb7df633.png)

**Comment by henon** [comment]
Can you try in an incognito window if it works for you?

**Comment by hburn7** [comment]
It does work in a Private window as well as other browsers.

**Comment by henon** [comment]
Then I suggest resetting the browser cache. Could be you got an old bugged version of the try.mudblazor webassembly in your firefox cache

**Comment by ScarletKuro** [comment]
Looks like same issue as here https://github.com/MudBlazor/MudBlazor/issues/6222?
It's weird, since I'm Firefox user, and I never had this problem, but it's the second user having the same issue and in both cases it works in the private tab. But looks more a bug in firefox or in blazor than in TryMudBlazor.

**Comment by ScarletKuro** [comment]
hi @hburn7,
Can you test now on Firefox without private tab?

**Comment by ScarletKuro** [comment]
Thanks for information. I guess we can close the issue then.

**Comment by hburn7** [comment]
Agreed, thanks!
