### ISSUE TITLE
Mudtable with Expansion Panels

### ISSUE THREAD

**Issue by stephanie-rimel** [MudBlazor/TryMudBlazor#137]
I have a Item data model with a List propery sessions, it is a 1 -> many relationship and I want to be able to have a table of expansion panels that open up to the itemized sessions and I can't figure out how to do this. Is there a way to alter the TableGroupDefinnition to have the parent object as the group by and the session id as the selector? Can i do some kind of renderfragment situation? Any ideas? I feel like this is a common data structure and would be a great addition to the componenets for mudtable. Thank you!

**Comment by danielchalmers** [comment]
Is this meant to be in TryMudBlazor?

**Comment by henon** [comment]
@stephanie-rimel please reopen the issue in the repository https://github.ocm/MudBlazor/MudBlazor
You can also join our discord to ask question in the help channel.
